config/routes.rb
Rails.application.routes.draw do
  # get 'searches/search'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :users
  root to: "homes#top"
  get "home/about"=>"homes#about"

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get :followers, on: :member
    get :followeds, on: :member
  end
  get "search" => "searches#search", as: 'search'

  resources :messages, only: [:create]
  resources :rooms, only: [:create, :show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates :comment, presence: true, length: {maximum: 100}
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    @comment = current_user.book_comments.new(book_comment_params)
    @comment.book_id = @book.id
    @book_comments = BookComment.all
    @comment.save
    @book_comment = BookComment.new
  end

  def destroy
    BookComment.find(params[:id]).destroy
    @book_comments = BookComment.all
    @book_comment = BookComment.new
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/views/book_comments/_form.html.erb
<%= form_with model: [book, book_comment], local: false do |f| %>
  <div class="form-group">
    <%= f.label :comment %>
    <%= f.text_area :comment, class: 'form-control comment' %>
  </div>
  <div class="form-group">
    <%= f.submit 'Send comment', class: 'btn btn-info btn-sm' %>
  </div>
<% end %>

app/views/book_comments/_index.html.erb
<div id="comment_index">
  <table class='table-sm'>
    <tbody>
      <% if book_comments.any? %>
        <% book_comments.each do |book_comment| %>
          <tr>
            <td>
              <%= link_to(book_comment.user) do %>
                <%= image_tag book_comment.user.get_profile_image, size:'50x50' %>
                <%= book_comment.user.name %>
              <% end %>
            </td>
            <td><%= book_comment.comment %></td>
            <% if book_comment.user == current_user %>
              <td><%= link_to 'Destroy', book_book_comment_path(book_comment.book, book_comment), method: :delete, data: {confirm: '本当に消しますか？' }, class: 'btn btn-danger btn-sm', remote: true %></td>
            <% end %>
          </tr>
        <% end %>
      <% else %>
      <p>No comment</p>
      <% end %>
    </tbody>
  </table>
</div>

app/views/book_comments/create.js.erb
$("textarea").val('');
$("#comment_index").html("<%= j(render 'book_comments/index', book_comments: @book_comments) %>");
$("#comment").html("<%= j(render 'book_comments/form', book: @book, book_comment: @book_comment) %>");

app/views/book_comments/destroy.js.erb
$("#comment_index").html("<%= j(render 'book_comments/index', book_comments: @book_comments) %>");