config/routes.rb
Rails.application.routes.draw do
  # get 'searches/search'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :users
  root to: "homes#top"
  get "home/about"=>"homes#about"

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get :followers, on: :member
    get :followeds, on: :member
  end
  get "search" => "searches#search", as: 'search'

  resources :messages, only: [:create]
  resources :rooms, only: [:create, :show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  is_impressionable

  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user
  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 200}

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  def self.looks(method, word)
    if method == 'perfect_match'
      @book = self.where("title LIKE? or body LIKE?","#{word}", "#{word}")
    elsif method == 'forward_match'
      @book = self.where("title LIKE? or body LIKE?","#{word}%", "#{word}%")
    elsif method == 'behind_match'
      @book = self.where("title LIKE? or body LIKE?","%#{word}", "#{word}%")
    elsif method == 'part_match'
      @book = self.where("title LIKE? or body LIKE?","%#{word}%", "#{word}%")
    end
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates :comment, presence: true, length: {maximum: 100}
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/message.rb
class Message < ApplicationRecord
  validates :talk, presence: true
  belongs_to :user
  belongs_to :room
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  # フォローする側
  belongs_to :follower, class_name: 'User'
  # フォローされる側
  belongs_to :followed, class_name: 'User'
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_one_attached :profile_image
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

# フォローする側
  has_many :relationships, foreign_key: :follower_id
  has_many :followers, through: :relationships, source: :followed

# フォローされる側
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: :followed_id
  has_many :followeds, through: :reverse_of_relationships, source: :follower

  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }



  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end

  def is_followed_by?(user)
    reverse_of_relationships.find_by(follower_id: user.id).present?
  end

  def self.looks(method, word)
    if method == 'perfect_match'
      @user = self.where("name LIKE?","#{word}")
    elsif method == 'forward_match'
      @user = self.where("name LIKE?","#{word}%")
    elsif method == 'behind_match'
      @user = self.where("name LIKE?","%#{word}")
    elsif method == 'part_match'
      @user = self.where("name LIKE?","%#{word}%")
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]
  impressionist :actions => [:show]

  def show
    @book = Book.find(params[:id])
    @user = User.find(@book.user_id)
    @nbook = Book.new
    @book_comment = BookComment.new
    @book_comments = BookComment.all
    impressionist(@book, nil, unique: [:session_hash.to_s])
  end

  def index
    to = Time.current.at_end_of_day
    from = (to - 6.day).at_beginning_of_day
    @books = Book.includes(:favorited_users).
      sort_by {|x|
        x.favorited_users.includes(:favorites).where(created_at: from..to).size}.reverse
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def is_matching_login_user
    @book = Book.find(params[:id])
    user_id = @book.user_id
    unless user_id == current_user.id
      redirect_to books_path
    end
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def create
    @room = Room.create
    @entry1 = Entry.create(room_id: @room.id, user_id: current_user.id)
    @entry2 = Entry.create(params.require(:entry).permit(:user_id, :room_id).merge(room_id: @room.id))
    redirect_to "/rooms/#{@room.id}"
  end

  def show
    @room = Room.find(params[:id])
    if Entry.where(user_id: current_user.id, room_id: @room.id).present?
      @messages = @room.messages
      @message = Message.new
      @entries = @room.entries.where.not(user_id: current_user.id)
    else
      redirect_back(fallback_location: root_path)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:update, :edit]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
    @currentUserEntry = Entry.where(user_id: current_user.id)
    @userEntry = Entry.where(user_id: @user.id)
    unless @user.id == current_user.id
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id then
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end
      if @isRoom
      else
        @room = Room.new
        @entry = Entry.new
      end
    end
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end

  def followers
    user = User.find(params[:id])
    @users = user.followers
  end

  def followeds
    user = User.find(params[:id])
    @users = user.followeds
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
<%= form_with model: book,local: true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="4"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to(book.user) do %>
          <%= image_tag book.user.get_profile_image, size:'80x80' %>
          <% end %>
        </td>
        <td><%= link_to book.title,book %></td>
        <td><%= book.body %></td>
        <td id="favorite_button_<%= book.id %>">
          <% if book.favorited_by?(current_user) %>
            <%= link_to book_favorites_path(book), method: :delete, remote: true do %>
              ♥︎<%= book.favorites.count %>
            <% end %>
          <% else %>
            <%= link_to book_favorites_path(book), method: :post, remote: true do %>
              ♡<%= book.favorites.count %>
            <% end %>
          <% end %>
        </td>
        <td>コメント数: <%= book.book_comments.count %></td>
        <td>閲覧数: <%= book.impressionist_count(:filter => :session_hash) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
  		<%= render 'layouts/errors', obj: @book %>
  		<%= render 'form', book: @book %>
  		<%= link_to 'Show', @book %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'layouts/errors', obj: @book %>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'index', books: @books %>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @nbook %>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		<table class='table'>
  		  <tr>
          <td><%= link_to(@book.user) do %>
            <%= image_tag @book.user.get_profile_image, size:"80x80" %><br>
            <%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, @book %></td>
          <td><%= @book.body %></td>
          <td id="favorite_button_<%= @book.id %>"><%= render 'favorites/favorite-btn', book: @book %></td>
          <td>コメント数: <%= @book.book_comments.count %></td>
          <td>閲覧数: <%= @book.impressionist_count(:filter => :session_hash) %></td>
          <% if @book.user == current_user %>
            <td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success" %></td>
            <td><%= link_to 'Destroy', @book, method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger"%></td>
          <% end %>
        </tr>
      </table>
      <h4>Comments</h4>
      <div id="comment_index"><%= render 'book_comments/index', book_comments: @book_comments %></div>
      <div id="comment"><%= render 'book_comments/form', book: @book, book_comment: @book_comment %></div>
    </div>
  </div>
</div>

app/views/rooms/show.html.erb
<% @entries.each do |e| %>
  <div class="user-name mx-2">
    <h2 class="rooms-title"><%= e.user.name %>さんとのチャット</h4>
  </div>
<% end %>
<hr>
<div class="chats container">
  <div class="chat row">
    <div class="col-md-6 mx-md-auto">
      <% if @messages.present? %>
        <% @messages.each do |m| %>
          <% if m.user == current_user %>
            <div class="d-flex flex-row-reverse bd-highlight">
              <div class="chat-face">
                <%= image_tag m.user.get_profile_image, size:'50x50', class:'user-image' %>
              </div>
              <div class="chat-hukidashi">
                <strong><%= m.talk %></strong> <br>
                <%= m.created_at.strftime("%Y-%m-%d %H:%M")%>
              </div>
            </div>
          <% else %>
            <div class="left-message">
              <div class="chat-face">
                <%= image_tag m.user.get_profile_image, size:'50x50', class:'user-image' %>
              </div>
              <div class="chat-hukidashi">
                <strong><%= m.talk %></strong> <br>
                <%= m.created_at.strftime("%Y-%m-%d %H:%M")%>
              </div>
            </div>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="col-md-6 mx-md-auto">
    <div class="posts">
      <%= form_with model: @message do |f| %>
        <%= f.text_field :talk, placeholder: "メッセージを入力して下さい", size: 52, class: 'form-text-field'%>
        <%= f.hidden_field :room_id, value: @room.id %>
        <%= f.submit "送信", class: 'form-submit' %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="4"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: '80x80' %></td>
        <td><%= user.name %></td>
        <td>フォロー数: <%= user.followers.count %></td>
        <td>フォロワー数: <%= user.followeds.count %></td>
        <td>
          <% unless user == current_user %>
            <% if user.is_followed_by?(current_user) %>
              <%= link_to "フォロー外す" ,user_relationships_path(user), method: :delete %>
            <% else %>
              <%= link_to "フォローする", user_relationships_path(user), method: :post %>
            <% end %>
          <% end %>
        </td>
        <td><%= link_to 'Show', user %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image, size:'100x100' %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>follows</th>
    <th><%= link_to user.followers.count, followers_user_path(user) %></th>
  </tr>
  <tr>
    <th>followers</th>
    <th><%= link_to user.followeds.count, followeds_user_path(user) %></th>
  </tr>
</table>

<div class='row'>
  <% if user == current_user %>
    <%= link_to edit_user_path(user.id), class: "btn btn-outline-secondary btn-block" do %>
      <i class="fas fa-user-cog"></i>
    <% end %>
  <% elsif user.is_followed_by?(current_user) %>
    <%= link_to user_relationships_path(user), method: :delete do %>
      <button class="btn btn-info">フォロー外す</button>
    <% end %>
    <% if (current_user.is_followed_by? user) && (user.is_followed_by? current_user) %>
      <% if @isRoom == true %>
        <p class="user-show-room"><a href="/rooms/<%= @roomId %>" class="btn btn-outline-secondary mx-4">Send chat</a></p>
      <% else %>
        <%= form_with model: @room do |f| %>
          <%= fields_for @entry do |e| %>
            <%= e.hidden_field :user_id, value: user.id %>
          <% end %>
          <%= f.submit "Start chat", class: 'btn btn-outline-info mx-4 user-show-chat'%>
        <% end %>
      <% end %>
    <% end %>
  <% else %>
    <%= link_to user_relationships_path(user), method: :post do %>
      <button class="btn btn-success">フォローする</button>
    <% end %>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/followeds.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-5">
      <h2>Follower Users</h2>
      <% if @users.empty? %>
        <p>ユーザーはいません</p>
      <% else %>
        <table class="table table-hover">
          <thead>
            <tr>
              <th>image</th>
              <th>name</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <% @users.each do |user| %>
                <%= link_to user_path(user) do %>
                  <td><%= image_tag user.get_profile_image, size: '80x80' %></td>
                  <td><%= user.name %></td>
                <% end %>
              <% end %>
            </tr>
          </tbody>
        </table>
      <% end %>
    </div>
  </div>
</div>

app/views/users/followers.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-5">
      <h2>Follow Users</h2>
      <% if @users.empty? %>
        <p>ユーザーはいません</p>
      <% else %>
        <table class="table table-hover">
          <thead>
            <tr>
              <th>image</th>
              <th>name</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <% @users.each do |user| %>
                <%= link_to user_path(user) do %>
                  <td><%= image_tag user.get_profile_image, size: '80x80' %></td>
                  <td><%= user.name %></td>
                <% end %>
              <% end %>
            </tr>
          </tbody>
        </table>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= render 'info', user: current_user %>

      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>


    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <%= render 'index',users: @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>
    </div>
  </div>
</div>